name: run

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  run:
    name: Run psalm (files, threads, psalm-version)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        files: [500, 512, 513]
        threads: [1, 2, 3]
        versions: ["dev-master", "5.25.0"]
    steps:
      - name: Setup PHP with specific version of PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: posix, pcntl

      - uses: actions/checkout@v3

      - name: Run composer install
        run: composer require vimeo/psalm:"${{ matrix.versions }}"

      - name: Run composer install
        run: composer install -o

      - name: Generate files
        run: php generate.php ${{ matrix.files }}

      - name: Run psalm 
        run: vendor/bin/psalm --no-cache --threads=${{ matrix.threads }}
